// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usr/jsonwebtoken/jwt_manager.go
//
// Generated by this command:
//
//	mockgen -source=internal/usr/jsonwebtoken/jwt_manager.go -destination=internal/usr/mocks/jwt_manager.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	jsonwebtoken "github.com/thestoicway/user_service/internal/usr/jsonwebtoken"
	gomock "go.uber.org/mock/gomock"
)

// MockJwtManager is a mock of JwtManager interface.
type MockJwtManager struct {
	ctrl     *gomock.Controller
	recorder *MockJwtManagerMockRecorder
}

// MockJwtManagerMockRecorder is the mock recorder for MockJwtManager.
type MockJwtManagerMockRecorder struct {
	mock *MockJwtManager
}

// NewMockJwtManager creates a new mock instance.
func NewMockJwtManager(ctrl *gomock.Controller) *MockJwtManager {
	mock := &MockJwtManager{ctrl: ctrl}
	mock.recorder = &MockJwtManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtManager) EXPECT() *MockJwtManagerMockRecorder {
	return m.recorder
}

// DecodeToken mocks base method.
func (m *MockJwtManager) DecodeToken(token string) (*jsonwebtoken.CustomClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeToken", token)
	ret0, _ := ret[0].(*jsonwebtoken.CustomClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeToken indicates an expected call of DecodeToken.
func (mr *MockJwtManagerMockRecorder) DecodeToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeToken", reflect.TypeOf((*MockJwtManager)(nil).DecodeToken), token)
}

// GenerateTokenPair mocks base method.
func (m *MockJwtManager) GenerateTokenPair(uuid uuid.UUID) (*jsonwebtoken.TokenPair, *jsonwebtoken.AdditionalInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenPair", uuid)
	ret0, _ := ret[0].(*jsonwebtoken.TokenPair)
	ret1, _ := ret[1].(*jsonwebtoken.AdditionalInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateTokenPair indicates an expected call of GenerateTokenPair.
func (mr *MockJwtManagerMockRecorder) GenerateTokenPair(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenPair", reflect.TypeOf((*MockJwtManager)(nil).GenerateTokenPair), uuid)
}
