name: User Service CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  user-service-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.4

      # Install dependencies
      - name: Get dependencies
        run: go get -v -t -d ./...

      # Build
      - name: Build
        run: go build -v ./...

      # Test
      - name: Test
        run: go test -v ./...
